name: monumental_habits_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  background_image: "assets/images/splash_bg.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/klasik-regular.otf
